<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-ITSGITUD" failures="1" tests="6" name="calc.testCases.CalcDemoTC.CalcTest" time="11.331" errors="0" timestamp="2023-10-05T10:21:30 IST" skipped="0">
  <testcase classname="calc.testCases.CalcDemoTC.CalcTest" name="VerifyCalcOperations" time="1.364"/>
  <testcase classname="calc.testCases.CalcDemoTC.CalcTest" name="VerifyCalcOperations" time="2.263"/>
  <testcase classname="calc.testCases.CalcDemoTC.CalcTest" name="VerifyCalcOperations" time="2.700">
    <failure message=" Actual value is : 2.0 Expected value is : 3.0 did not expect to find [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError:  Actual value is : 2.0 Expected value is : 3.0 did not expect to find [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at calc.utility.reports.Reporter.logFail(Reporter.java:153)
at calc.utility.reports.Reporter.logIntoReport(Reporter.java:128)
at calc.wspages.calcDemo.WebCalcLoad.validateResult(WebCalcLoad.java:211)
at calc.testCases.CalcDemoTC.CalcTest.VerifyCalcOperations(CalcTest.java:53)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </failure>
  </testcase> <!-- VerifyCalcOperations -->
  <testcase classname="calc.testCases.CalcDemoTC.CalcTest" name="VerifyCalcOperations" time="2.447"/>
  <testcase classname="calc.testCases.CalcDemoTC.CalcTest" name="VerifyCalcOperations" time="1.257"/>
  <testcase classname="calc.testCases.CalcDemoTC.CalcTest" name="VerifyCalcOperations" time="1.300"/>
</testsuite> <!-- calc.testCases.CalcDemoTC.CalcTest -->
